site_name: test

site_url: https://zyang91.github.io/night-light-analysis/

repo_url: https://github.com/zyang91/night-light-analysis

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: True

        execute: True
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true


nav:
    - Home: README.md
    - Example:
        - sample.ipynb
        - test.ipynb
  